build: p1 p2 p3 p4

p1: src/p1.cpp
	g++ -std=c++17 -Wall -Wextra src/p1.cpp -o p1

p2: src/p2.cpp
	g++ -std=c++17 -Wall -Wextra src/p2.cpp -o p2

p3: src/p3.cpp
	g++ -std=c++17 -Wall -Wextra src/p3.cpp -o p3

p4: src/bonus.cpp
	g++ -std=c++17 -Wall -Wextra src/bonus.cpp -o p4

run-p1:
	./p1
run-p2:
	./p2
run-p3:
	./p3
run-p4:
	./p4

clean:
	rm -f p1 p2 p3 p4
